apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akita-gpb-hooks-module
  title: Akita-gpb-hooks-module
  description: Сервис akita-gpb-hooks-module содержит хуки для фреймворка Akita-BDD, включая Allure (интеграция с Selenium, RestAssured и цензура паролей) и Docker (запуск и остановка Docker Compose)
  annotations:
    backstage.io/techdocs-ref: dir:./techdocs
  tags:
    - akita-gpb
    - testing
    - akita-gpb-hooks-module
    - akita
    - akitagpb
spec:
  type: library
  lifecycle: production
  owner: qa-tools-team