apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akita-gpb-db-module
  title: Akita-gpb-db-module
  description: Сервис akita-gpb-db-module обеспечивает взаимодействие с базами данных через выполнение SQL-запросов и обработку результатов
  annotations:
    backstage.io/techdocs-ref: dir:./techdocs
  tags:
    - akita-gpb
    - testing
    - akita-gpb-db-module
    - akita
    - akitagpb
spec:
  type: library
  lifecycle: production
  owner: qa-tools-team