apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akita-gpb-api-module
  title: Akita-gpb-api-module
  description: Сервис akita-gpb-api-module предназначен для упрощения автоматизации тестирования API в рамках фреймворка Akita-BDD
  annotations:
    backstage.io/techdocs-ref: dir:./techdocs
  tags:
    - akita-gpb
    - testing
    - akita-gpb-api-module
    - akita
    - akitagpb
spec:
  type: library
  lifecycle: production
  owner: qa-tools-team