apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akita-gpb-helpers-module
  title: Akita-gpb-helpers-module
  description: Сервис akita-gpb-helpers-module содержит абстрактные вспомогательные классы, не связанные с базовыми модулями, такие как DockerHelper, SshConnectionHelper и SshSteps
  annotations:
    backstage.io/techdocs-ref: dir:./techdocs
  tags:
    - akita-gpb
    - testing
    - akita-gpb-helpers-module
    - akita
    - akitagpb
spec:
  type: library
  lifecycle: production
  owner: qa-tools-team