apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akita-gpb-core-module
  title: Akita-gpb-core-module
  description: Сервис akita-gpb-core-module является ядром фреймворка Akita-BDD, отвечающим за основную логику и функциональность
  annotations:
    backstage.io/techdocs-ref: dir:./techdocs
  tags:
    - akita-gpb
    - testing
    - akita-gpb-core-module
    - akita
    - akitagpb
spec:
  type: library
  lifecycle: production
  owner: qa-tools-team