apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akita-gpb-kafka-mq-module
  title: Akita-gpb-kafka-mq-module
  description: Сервис akita-gpb-kafka-mq-module предназначен для взаимодействия с системами обмена сообщениями и стриминговыми платформами в фреймворке Akita-BDD
  annotations:
    backstage.io/techdocs-ref: dir:./techdocs
  tags:
    - akita-gpb
    - testing
    - akita-gpb-kafka-mq-module
    - akita
    - akitagpb
spec:
  type: library
  lifecycle: production
  owner: qa-tools-team