site_name: 'akita-gpb-kafka-mq-module'
site_description: 'Документация фреймворка Akita-GPB'
repo_url: https://bitbucket.dev.gazprombank.ru/projects/QA/repos/akita-gpb-docs/browse/docs
nav:
  - Главная: README.md
plugins:
  - techdocs-core
  - search
  - panzoom
  - kroki